99cats/config/routes.rb
Rails.application.routes.draw do
  resources :cats, except: [:destroy] do
    resources :cat_rental_requests, as: "rentals", path:"rentals", except: [:show,:create,:new]
  end

   #only: [:index, :show, :new, :create,:edit,:update]
  resources :cat_rental_requests, as: "rentals", path: "rentals", only: [:show,:create,:new]
end

99cats/app/models/cat.rb
class Cat < ActiveRecord::Base
  COLORS = {
    white: 0xFFFFFF,
    black: 0x000000,
    brown: 0x5C3317}

    COLOR_VALUES = {
      0xFFFFFF => "White",
      0x000000 => "Black",
      0x5C3317 => "Brown"}


  def self.colors
    COLORS
  end

  validates :birth_date, presence: true
  validates :name, presence: true
  validates :sex, inclusion: {in: %w(M F)}
  validates :color, inclusion: Cat.colors.values, allow_blank: true

  has_many :rentals, class_name: "CatRentalRequest"

  def age
    Time.now.year - birth_date.year
  end
end

99cats/app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  def overlapping_requests
    requests = CatRentalRequest
      .where.not("? < ALL (cat_rental_requests.end_date,cat_rental_requests.start_date)", end_date)
      .where.not("? > ALL (cat_rental_requests.end_date,cat_rental_requests.start_date)", start_date)
      .where(cat_id: cat_id)
      .where.not(id: id)

  end
  #
  def overlapping_approved_requests
    if status == "approved" && overlapping_requests.where(status: "approved").count > 0
      errors[:status] << "can't approve overlapping requests"
    end
  end

  def start_before_end_date
    if end_date < start_date
      errors[:start_date] << "start date must be before end date"
    end
  end

  def approve!
    if overlapping_requests.where(status: "approved").count > 0
      raise "There is already an approved request for those dates"
    else
      # @status = "approved"
      CatRentalRequest.transaction do
        update!(status: "approved")
        overlapping_requests.where(status: "pending").each do |request|
          request.deny!
        end
      end
    end
  end

  def deny!
    # @status = "denied"
    update(status: "denied")
  end

  validates :status, inclusion: %w(pending approved denied)
  validate :overlapping_approved_requests
  validate :start_before_end_date
  belongs_to :cat, :dependent => :destroy


end

99cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

99cats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def index
    @cat = Cat.find(params[:cat_id])
    @rentals = CatRentalRequest.where(cat_id: @cat.id)
    render :index
  end

  def show
    @rental = CatRentalRequest.find(params[:id])
    render :show
  end

  def create
    @rental = CatRentalRequest.new(rental_params)
    if @rental.save
      redirect_to rental_url(@rental)
    else
      render @rental.errors.full_messages, status: :unprocessable_entity
    end
  end

  def new
    @rental = CatRentalRequest.new
    @cats = Cat.all
    render :new
  end

  def edit
  end

  def update
  end

  private
  def rental_params
   params.
     require(:cat_rental_request).
     permit(:cat_id,:start_date,:end_date)
  end
end

99cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render @cat.errors.full_messages, status: :unprocessable_entity
    end
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update
    @cat = Cat.find_by(id: params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render @cat.errors.full_messages, status: :unprocessable_entity
    end
  end

  private
  def cat_params
   params.
     require(:cat).
     permit(:name, :birth_date, :sex, :description, :color)
  end
end

99cats/app/helpers/application_helper.rb
module ApplicationHelper
end

99cats/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

99cats/app/helpers/cats_helper.rb
module CatsHelper
end

99cats/app/views/cat_rental_requests/index.html.erb
<h1> Rentals for <%= @cat.name %> </h1>

<% @rentals.each do |rental| %>
  Start Date: <%= rental.start_date %>
  End Date: <%= rental.end_date %>
  Status: <%= rental.status %>
  <br>

    <%= link_to "Index", cats_url %>
<% end %>

99cats/app/views/cat_rental_requests/new.html.erb
<h1>Make a new rental</h1>
<form action="<%= rentals_url %>" method="post">
  <label for="start_date">Pick a Start Date</label>
  <input type="date" name="cat_rental_request[start_date]" id="start_date">
  <br>
  <label for="end_date">Pick an End Date</label>
  <input type="date" name="cat_rental_request[end_date]" id="end_date">
  <br>
  <label for="which_cat">Choose a cat</label>
  <select name="cat_rental_request[cat_id]">
    <% @cats.each do |cat| %>
      <option value="<%= cat.id %>"><%= cat.name %></option>
    <% end %>
  </select>
  <input type="submit" value="Submit dates">
</form>

99cats/app/views/cat_rental_requests/show.html.erb
<body>
  <h1>Here is your rental details for <%= @rental.cat.name %>! </h1>


  <table>
    <tr>
      <th>Start Date: </th>
      <th>End Date: </th>
      <th>Status</th>
    </tr>
    <tr>
        <td><%= @rental.start_date %></td>
        <td><%= @rental.end_date %></td>
        <td><%= @rental.status %></td>
    </tr>

  </table>

  <%= link_to "Index", cats_url %>

</body>

99cats/app/views/cats/_form.html.erb
<% action_url = (action == :new) ? cats_url : cat_url(cat) %>
<% request_type = (action == :new) ? "post" : "patch" %>
<% button_prompt = (action == :new) ? "Create cat!" : "Save cat!" %>
<form action="<%= action_url %>" method="post">
  <input type="hidden" name="_method" value="<%= request_type %>"/>
  <label for="cat_name">First name</label>
  <input type="text" name="cat[name]" id="cat_name" value="<%= cat.name %>">
  <br>
  <label for="cat_birth_date">Birth date</label>
  <input name="cat[birth_date]" id="cat_birth_date" type="date" value="<%= cat.birth_date %>">
  <br>
  <label>Sex</label>
  <div>
    <input name="cat[sex]" id="cat_sex_m" type="radio" value="M" <%= "checked" if cat.sex == "M" %>>
    <label for="cat_sex_m">Male</label>
    <input name="cat[sex]" id="cat_sex_f" type="radio" value="F" <%= "checked" if cat.sex == "F" %>>
    <label for="cat_sex_f">Female</label>
  </div>

  <label for="cat_description">Description</label>
  <textarea name="cat[description]" id="cat_description" ><%= cat.description %></textarea>
  <br>

  <label for="cat_coat_color">Coat color</label>
  <select name="cat[color]">
    <%# Cat::COLORS.each_key do |color| %>
    <option value="<%= Cat.colors[:brown] %>">Brown</option>
    <option value="<%= Cat.colors[:black] %>">Black</option>
    <option value="<%= Cat.colors[:white] %>">White</option>
  </select>
  <input type="submit" value="<%= button_prompt %>">

</form>

99cats/app/views/cats/edit.html.erb
<h1> Edit your cat!</h1>

<%= render "form", cat: @cat, action: :edit %>

99cats/app/views/cats/index.html.erb
<body>
  <h1>Here are the cats</h1>
  <% @cats.each do |cat| %>
  <%= link_to cat.name, cat_url(cat)%> <br>
  <% end %>
<br>
<%= link_to "+ New cat", new_cat_url %>
<%= link_to "+ New rental", new_rental_url  %>
</body>

99cats/app/views/cats/new.html.erb
<h1> Create a new cat!</h1>
<%= render "form", cat: @cat, action: :new%>
<!-- <form action="/cats" method="post">
  <label for="cat_name">First name</label>
  <input type="text" name="cat[name]" id="cat_name">
  <br>
  <label for="cat_birth_date">Birth date</label>
  <input name="cat[birth_date]" id="cat_birth_date" type="date">
  <br>
  <label>Sex</label>
  <div>
    <input name="cat[sex]" id="cat_sex_m" type="radio" value="M">
    <label for="cat_sex_m">Male</label>
    <input name="cat[sex]" id="cat_sex_f" type="radio" value="F">
    <label for="cat_sex_f">Female</label>
  </div>

  <label for="cat_description">Description</label>
  <textarea name="cat[description]" id="cat_description"></textarea>
  <br>

  <input type="submit" value="Create cat!"> -->

<!-- TODO ask for colors -->
  <!-- <label for="cat_coat_color">Coat color</label> -->
  <!-- dropdown -->
  <!-- <select name="cat[coat_color]"> -->
    <!-- `brown` is the value that will be submitted to the server; user is
         displayed "Brown" as the choice -->
    <!-- <option value="brown">Brown</option> -->
    <!-- <option value="black">Black</option>
    <option value="blue">Blue</option>
  </select> -->
<!-- </form> -->

99cats/app/views/cats/show.html.erb
<body>
  <h1>Here is <%= @cat.name %>! </h1>


  <table>
    <tr>
      <th>Age: </th>
      <th>Sex: </th>
      <th>Color: </th>
      <th>Description</th>
    </tr>
    <tr>
        <td><%= @cat.age %></td>
        <td><%= @cat.sex %></td>
        <td><%= Cat::COLOR_VALUES[@cat.color] %></td>
        <td><%= @cat.description %></td>
    </tr>

  </table>
  <%= link_to "Edit", edit_cat_url(@cat) %>
  <%= link_to "Index", cats_url %>
  <%= link_to "See rentals",cat_rentals_url(@cat) %>
</body>

99cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ninetyninecats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>